"""
micro_saas_forge - From idea to deployable revenue unit in one call.

Not another scanner. This BUILDS.
Takes a niche + problem → outputs complete micro-SaaS:
  - FastAPI backend skeleton (copy-paste deployable)
  - Stripe integration for payments
  - Landing page HTML with pricing
  - Revenue model with unit economics

Usage:
  skill_executor.py micro_saas_forge '{"niche": "freelance designers", "problem": "invoice tracking", "price_mo": 19}'
  skill_executor.py micro_saas_forge '{"niche": "youtube creators", "problem": "thumbnail A/B testing", "price_mo": 29}'
"""

import json
import os
import re
from datetime import datetime
from pathlib import Path


def _slug(name: str) -> str:
    return re.sub(r'[^a-z0-9]+', '_', name.lower()).strip('_')


def _gen_backend(app_name: str, slug: str, problem: str, price_cents: int) -> str:
    return f'''#!/usr/bin/env python3
"""
{app_name} — Micro-SaaS Backend
Auto-generated by Wave micro_saas_forge
"""
from fastapi import FastAPI, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import stripe
import os
import uvicorn

app = FastAPI(title="{app_name}", version="0.1.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

stripe.api_key = os.getenv("STRIPE_SECRET_KEY", "sk_test_placeholder")
PRICE_ID = os.getenv("STRIPE_PRICE_ID", "price_placeholder")

# ── In-memory store (swap for Postgres/SQLite in prod) ──
users_db = {{}}

class SignupRequest(BaseModel):
    email: str
    name: str = ""

class WebhookEvent(BaseModel):
    pass

@app.get("/")
def root():
    return {{"app": "{app_name}", "status": "live", "problem_solved": "{problem}"}}

@app.post("/api/signup")
def signup(req: SignupRequest):
    """Free tier signup — collects lead, creates Stripe customer."""
    import stripe as s
    customer = s.Customer.create(email=req.email, name=req.name)
    users_db[req.email] = {{"stripe_id": customer.id, "plan": "free", "created": str(__import__("datetime").datetime.utcnow())}}
    return {{"ok": True, "customer_id": customer.id}}

@app.post("/api/checkout")
def create_checkout(email: str):
    """Creates Stripe Checkout session for ${price_cents // 100}/mo plan."""
    user = users_db.get(email)
    if not user:
        raise HTTPException(404, "Sign up first")
    session = stripe.checkout.Session.create(
        customer=user["stripe_id"],
        line_items=[{{"price": PRICE_ID, "quantity": 1}}],
        mode="subscription",
        success_url=os.getenv("SUCCESS_URL", "https://yourapp.com/success"),
        cancel_url=os.getenv("CANCEL_URL", "https://yourapp.com/cancel"),
    )
    return {{"checkout_url": session.url}}

@app.post("/api/webhook")
async def stripe_webhook(request: Request):
    """Handle Stripe subscription events."""
    payload = await request.body()
    sig = request.headers.get("stripe-signature", "")
    endpoint_secret = os.getenv("STRIPE_WEBHOOK_SECRET", "whsec_placeholder")
    try:
        event = stripe.Webhook.construct_event(payload, sig, endpoint_secret)
    except Exception:
        raise HTTPException(400, "Invalid webhook")
    
    if event["type"] == "checkout.session.completed":
        cust = event["data"]["object"]["customer"]
        for email, u in users_db.items():
            if u["stripe_id"] == cust:
                u["plan"] = "pro"
                break
    return {{"received": True}}

# ── Core feature endpoints (customize these) ──
@app.get("/api/dashboard")
def dashboard(email: str):
    user = users_db.get(email)
    if not user:
        raise HTTPException(404)
    return {{"plan": user["plan"], "usage": {{}}, "message": "Build your core feature here"}}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", "8000")))
'''


def _gen_landing(app_name: str, niche: str, problem: str, price_mo: int) -> str:
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{app_name} — {problem.title()} for {niche.title()}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#1a1a2e;background:#fafafa}}
.hero{{text-align:center;padding:80px 20px 60px;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff}}
.hero h1{{font-size:2.8rem;margin-bottom:16px;font-weight:800}}
.hero p{{font-size:1.3rem;opacity:.9;max-width:600px;margin:0 auto 32px}}
.cta{{display:inline-block;padding:16px 48px;background:#fff;color:#764ba2;font-size:1.1rem;font-weight:700;border-radius:8px;text-decoration:none;transition:transform .2s}}
.cta:hover{{transform:translateY(-2px)}}
.features{{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:32px;max-width:960px;margin:60px auto;padding:0 20px}}
.feature{{background:#fff;padding:32px;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,.06)}}
.feature h3{{font-size:1.2rem;margin-bottom:8px;color:#764ba2}}
.pricing{{text-align:center;padding:60px 20px;background:#fff}}
.pricing h2{{font-size:2rem;margin-bottom:40px}}
.price-card{{display:inline-block;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;padding:48px;border-radius:16px;min-width:300px}}
.price-card .amount{{font-size:3rem;font-weight:800}}
.price-card .period{{font-size:1rem;opacity:.8}}
.price-card ul{{text-align:left;margin:24px 0;list-style:none}}
.price-card li::before{{content:"✓ ";color:#a0f0a0}}
.footer{{text-align:center;padding:40px;color:#888;font-size:.9rem}}
</style>
</head>
<body>
<div class="hero">
  <h1>{app_name}</h1>
  <p>{problem.title()} — built specifically for {niche.lower()}. Stop wasting time. Start getting paid.</p>
  <a href="#pricing" class="cta">Start Free Trial →</a>
</div>
<div class="features">
  <div class="feature"><h3>⚡ Built for {niche.title()}</h3><p>Not another generic tool. Every feature designed around how {niche.lower()} actually work.</p></div>
  <div class="feature"><h3>🔒 Secure & Reliable</h3><p>Bank-level encryption. 99.9% uptime. Your data stays yours.</p></div>
  <div class="feature"><h3>🚀 Setup in 2 Minutes</h3><p>No complex onboarding. Connect your accounts and go.</p></div>
</div>
<div class="pricing" id="pricing">
  <h2>Simple Pricing</h2>
  <div class="price-card">
    <div class="amount">${price_mo}</div>
    <div class="period">per month</div>
    <ul>
      <li>Unlimited {problem.lower()}</li>
      <li>Priority support</li>
      <li>API access</li>
      <li>14-day free trial</li>
    </ul>
    <a href="/api/checkout" class="cta" style="color:#764ba2">Start Free Trial</a>
  </div>
</div>
<div class="footer">© {datetime.now().year} {app_name}. Built with precision.</div>
</body>
</html>'''


def _gen_dockerfile(slug: str) -> str:
    return f'''FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''


def _gen_requirements() -> str:
    return "fastapi==0.115.0\nuvicorn==0.30.0\nstripe==10.0.0\npython-dotenv==1.0.1\n"


def _revenue_model(price_mo: int, niche: str) -> dict:
    """Unit economics projection."""
    cac_estimate = round(price_mo * 2.5)  # conservative 2.5x monthly
    ltv_months = 14  # avg SaaS retention
    ltv = price_mo * ltv_months
    ltv_cac = round(ltv / max(cac_estimate, 1), 1)
    
    projections = {}
    customers = 0
    for month in range(1, 13):
        new = max(3, int(month * 2.5))  # organic growth curve
        churn = int(customers * 0.05)  # 5% monthly churn
        customers = customers + new - churn
        mrr = customers * price_mo
        projections[f"month_{month}"] = {"customers": customers, "mrr": mrr, "arr": mrr * 12}
    
    return {
        "price_monthly": price_mo,
        "estimated_cac": cac_estimate,
        "ltv": ltv,
        "ltv_cac_ratio": ltv_cac,
        "break_even_customers": max(1, round(500 / price_mo)),  # assuming $500/mo infra
        "year_1_projection": projections,
        "month_12_mrr": projections["month_12"]["mrr"],
        "month_12_arr": projections["month_12"]["arr"],
    }


def run(params: dict) -> dict:
    niche = params.get("niche", "solopreneurs")
    problem = params.get("problem", "workflow automation")
    price_mo = params.get("price_mo", 29)
    save = params.get("save", False)
    output_dir = params.get("output_dir", "")
    
    price_cents = price_mo * 100
    app_name = problem.replace(" ", "").title().replace(" ", "")
    if len(app_name) > 20:
        app_name = app_name[:20]
    slug = _slug(problem)
    
    backend = _gen_backend(app_name, slug, problem, price_cents)
    landing = _gen_landing(app_name, niche, problem, price_mo)
    dockerfile = _gen_dockerfile(slug)
    requirements = _gen_requirements()
    revenue = _revenue_model(price_mo, niche)
    
    result = {
        "success": True,
        "app_name": app_name,
        "niche": niche,
        "problem": problem,
        "files": {
            "main.py": backend,
            "index.html": landing,
            "Dockerfile": dockerfile,
            "requirements.txt": requirements,
            ".env.example": f"STRIPE_SECRET_KEY=sk_test_...\nSTRIPE_PRICE_ID=price_...\nSTRIPE_WEBHOOK_SECRET=whsec_...\nSUCCESS_URL=https://{slug}.com/success\nCANCEL_URL=https://{slug}.com/cancel\nPORT=8000\n",
        },
        "revenue_model": revenue,
        "deploy_commands": [
            f"mkdir -p {slug} && cd {slug}",
            "# Copy generated files into directory",
            "docker build -t " + slug + " .",
            "docker run -p 8000:8000 --env-file .env " + slug,
            "# Or deploy to Railway/Render/Fly.io in 1 click",
        ],
        "next_steps": [
            "1. Create Stripe account → get API keys",
            "2. Create a Product + Price in Stripe dashboard",
            "3. Customize the /api/dashboard endpoint with core feature",
            "4. Deploy (Railway recommended: railway up)",
            f"5. Target {niche} communities — Reddit, Discord, Twitter",
            f"6. Goal: 10 paying customers = ${price_mo * 10}/mo MRR",
        ],
    }
    
    if save and output_dir:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        for fname, content in result["files"].items():
            (out / fname).write_text(content)
        result["saved_to"] = str(out)
    
    return result
