"""add_brand_guidelines_and_compliance_columns

Revision ID: 0e89aff23815
Revises: 53cd94dadb9f
Create Date: 2026-03-18 00:19:13.951615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e89aff23815'
down_revision: Union[str, None] = '53cd94dadb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_guidelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('secondary_colors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fonts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('logo_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tone_description', sa.Text(), nullable=True),
    sa.Column('dos', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('donts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('custom_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_guidelines_tenant_id'), 'brand_guidelines', ['tenant_id'], unique=False)
    op.add_column('media_assets', sa.Column('compliance_score', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('compliance_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'compliance_issues')
    op.drop_column('media_assets', 'compliance_score')
    op.drop_index(op.f('ix_brand_guidelines_tenant_id'), table_name='brand_guidelines')
    op.drop_table('brand_guidelines')
    # ### end Alembic commands ###
