"""add_trend_entries

Revision ID: 53cd94dadb9f
Revises: 35b1e5413d89
Create Date: 2026-03-18 00:09:17.622787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cd94dadb9f'
down_revision: Union[str, None] = '35b1e5413d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('google_trends', 'x_twitter', 'combined', name='trend_source'), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('volume_change_pct', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('ai_caption_draft', sa.Text(), nullable=True),
    sa.Column('ai_hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_entries_tenant_id'), 'trend_entries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_entries_tenant_id'), table_name='trend_entries')
    op.drop_table('trend_entries')
    # ### end Alembic commands ###
